//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblBill()
        {
            this.TblBillInfors = new HashSet<TblBillInfor>();
        }
    
        public int ID { get; set; }
        public int TableID { get; set; }
        public System.DateTime DateCheckIn { get; set; }
        public Nullable<System.DateTime> DateCheckOut { get; set; }
        public string BillStatus { get; set; }
        public double TotalBill { get; set; }
    
        public virtual TblTable TblTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBillInfor> TblBillInfors { get; set; }
    }
}
