//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblBillInfor
    {
        public int ID { get; set; }
        public int BillID { get; set; }
        public int FoodID { get; set; }
        public int CountF { get; set; }
        public double Total { get; set; }
    
        public virtual TblBill TblBill { get; set; }
        public virtual TblFood TblFood { get; set; }
    }
}
