//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_Shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTable()
        {
            this.TblBills = new HashSet<TblBill>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string TableStatus { get; set; }
        public string Location { get; set; }
        public string TableType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblBill> TblBills { get; set; }
    }
}
